blank_issues_enabled: true
contact_links:
  - name: Questions and discussion
    url: https://github.com/zhouzhih/typing-beginner/discussions
    about: Use Discussions for open-ended ideas and questions.
